export const peers = [
  {
    id: 1,
    name: "Maya R.",
    age: 19,
    location: "Phoenix, AZ",
    state: "AZ",
    project: "Voter registration drives at community colleges",
    skill: "Collaborating",
    bio: "Maya is organizing campus-wide voter registration events across Maricopa County community colleges, building peer networks to sustain civic participation beyond election cycles.",
    interests: ["Voter Rights", "Campus Organizing", "Coalition Building"],
  },
  {
    id: 2,
    name: "James K.",
    age: 21,
    location: "Atlanta, GA",
    state: "GA",
    project: "Food access mapping and advocacy",
    skill: "Credible Information",
    bio: "James is building an open-source data layer to map food deserts in metro Atlanta, working with neighborhood associations to turn that data into policy asks.",
    interests: ["Food Justice", "Open Data", "Policy Advocacy"],
  },
  {
    id: 3,
    name: "Sofia L.",
    age: 17,
    location: "Tampa, FL",
    state: "FL",
    project: "Disaster preparedness outreach for families",
    skill: "Collaborating",
    bio: "Sofia developed a multilingual disaster preparedness guide for low-income families in Tampa Bay, now distributing through 14 community organizations.",
    interests: ["Emergency Preparedness", "Multilingual Access", "Community Resilience"],
  },
  {
    id: 4,
    name: "Andre W.",
    age: 20,
    location: "Detroit, MI",
    state: "MI",
    project: "Youth civic tech mentorship program",
    skill: "Productive Conversations",
    bio: "Andre runs a mentorship program pairing high school students with civic technologists, helping young people build tools for community accountability.",
    interests: ["Civic Tech", "Youth Mentorship", "Accountability"],
  },
  {
    id: 5,
    name: "Priya M.",
    age: 18,
    location: "San Jose, CA",
    state: "CA",
    project: "Multilingual civic information hub",
    skill: "Credible Information",
    bio: "Priya built a civic information platform available in 8 languages, helping recent immigrant families understand local government processes in Silicon Valley.",
    interests: ["Language Access", "Immigrant Rights", "Civic Education"],
  },
  {
    id: 6,
    name: "Carlos D.",
    age: 22,
    location: "Houston, TX",
    state: "TX",
    project: "Community land trust advocacy",
    skill: "Productive Conversations",
    bio: "Carlos is working with longtime residents in Houston's Third Ward to establish a community land trust that keeps housing affordable for the next generation.",
    interests: ["Housing Justice", "Land Policy", "Community Organizing"],
  },
  {
    id: 7,
    name: "Zara H.",
    age: 16,
    location: "Minneapolis, MN",
    state: "MN",
    project: "Youth-led school board engagement",
    skill: "Productive Conversations",
    bio: "Zara organized a coalition of Minneapolis students to present a unified platform to their school board on mental health resources and curriculum equity.",
    interests: ["Education Equity", "Mental Health", "Youth Voice"],
  },
  {
    id: 8,
    name: "Liam O.",
    age: 23,
    location: "Boston, MA",
    state: "MA",
    project: "Open data civic accountability tool",
    skill: "Credible Information",
    bio: "Liam built a public-facing tool that tracks city council voting records against campaign promises, used by three Boston neighborhood organizations.",
    interests: ["Transparency", "Open Data", "Local Government"],
  },
];

export const civicActions = [
  {
    id: 1,
    title: "Join Your Local Climate Action Council",
    skill: "Collaborating to Create Solutions",
    location: "Phoenix, AZ",
    description: "Connect with 12 other young people working on heat resilience in Maricopa County.",
    detail: "This council meets monthly to coordinate youth-led climate adaptation projects in the Phoenix metro area. Activities include community heat mapping, advocating for cool corridor infrastructure, and presenting findings to the Maricopa County Board of Supervisors. No prior experience required — just genuine interest in making Phoenix more livable.",
    commitment: "2–4 hrs/month",
    format: "In-person + virtual",
  },
  {
    id: 2,
    title: "Evaluate News Sources on Immigration Policy",
    skill: "Credible Information",
    location: "National",
    description: "A 20-minute guided exercise to assess credibility of three recent immigration news stories.",
    detail: "Using C&S's structured credibility framework, you'll evaluate sourcing, perspective balance, and factual accuracy in three recent immigration stories from outlets across the political spectrum. You'll earn a Credible Information skill milestone and receive a personalized report on your reasoning patterns.",
    commitment: "20 minutes",
    format: "Self-guided online",
  },
  {
    id: 3,
    title: "Collaborate on a Food Access Proposal",
    skill: "Productive Conversations",
    location: "Chicago, IL",
    description: "Join a working group drafting a food access proposal for the South Side Community Board.",
    detail: "This working group is preparing a formal proposal for Chicago's 6th District Community Board requesting a fresh produce subsidy program for corner stores. You'll contribute research, help facilitate community listening sessions, and co-author sections of the final proposal. Strong writing or community organizing experience is a plus.",
    commitment: "5–8 hrs over 3 weeks",
    format: "Virtual + 1 in-person session (Chicago)",
  },
  {
    id: 4,
    title: "Attend a Virtual Town Hall on Youth Mental Health",
    skill: "Productive Conversations",
    location: "Virtual",
    description: "State legislators are hearing from young people on mental health funding priorities.",
    detail: "State representatives from 12 districts are holding a virtual listening session specifically for residents ages 14–24. Share your experience with school mental health resources — or the lack of them — and help shape the next state budget cycle. Registration is free and takes 2 minutes.",
    commitment: "90 minutes",
    format: "Virtual",
  },
  {
    id: 5,
    title: "Map Your Community's Civic Resources",
    skill: "Credible Information",
    location: "Any US City",
    description: "Use our mapping tool to document public meeting spaces, libraries, and civic organizations near you.",
    detail: "C&S's Civic Resource Mapper lets you build a verified, shareable directory of civic infrastructure in your neighborhood — from public library meeting rooms to community gardens to neighborhood associations. Your contributions feed into a national open dataset used by organizers, researchers, and local governments.",
    commitment: "1–2 hrs",
    format: "Self-guided online",
  },
  {
    id: 6,
    title: "Organize a Neighborhood Clean-Up Day",
    skill: "Collaborating to Create Solutions",
    location: "Your Neighborhood",
    description: "Plan and lead a community clean-up with at least 10 participants. We provide the toolkit.",
    detail: "C&S provides a complete organizer toolkit: outreach templates, a participant sign-in system, photo documentation guidelines, and a post-event impact report generator. Clean-ups that meet the 10-participant threshold count toward your Collaborating to Create Solutions portfolio milestone.",
    commitment: "4–6 hrs planning + event day",
    format: "In-person",
  },
];

export const programs = [
  {
    id: 1,
    name: "Carnegie Young Leaders",
    category: "Team Grant",
    ageRange: "14–24",
    duration: "12 months",
    format: "Hybrid",
    skills: ["Collaborating to Create Solutions", "Productive Conversations"],
    description: "Year-long program for teams of young people working on sustained community projects. Coaching, a national peer network, and project support.",
    status: "Applications Open",
    deadline: "Rolling admissions",
    detail: "Carnegie Young Leaders supports teams of 3–6 young people (ages 14–24) working on sustained community improvement projects. Teams receive structured coaching, access to a national peer network, project planning resources, and presentation opportunities at regional convenings. Applications are reviewed on a rolling basis — teams can apply at any stage of their project.",
    cohortSize: "Up to 40 teams",
    location: "National",
  },
  {
    id: 2,
    name: "Civic Spring Fellowship",
    category: "Fellowship",
    ageRange: "18–24",
    duration: "10 weeks",
    format: "Virtual + 2 in-person convenings",
    skills: ["Productive Conversations", "Credible Information"],
    description: "Intensive fellowship for young civic actors ready to move from project to movement. Mentorship, skill-building, and a cohort experience.",
    status: "Coming Soon",
    deadline: "Applications open Summer 2026",
    detail: "Civic Spring is a 10-week intensive fellowship for young civic leaders ages 18–24 who are ready to move from project to movement. Fellows are matched with a practicing civic professional mentor, participate in weekly cohort skill-building sessions, and complete a capstone project presented to community stakeholders. The inaugural cohort launches Fall 2026.",
    cohortSize: "24 fellows",
    location: "National (virtual-first)",
  },
  {
    id: 3,
    name: "Local Democracy Lab",
    category: "Skills Pathway",
    ageRange: "16–22",
    duration: "6 weeks",
    format: "Fully virtual, self-paced",
    skills: ["Credible Information", "Productive Conversations"],
    description: "A structured online pathway teaching young people how local government actually works — zoning, budgets, school boards — and how to engage it effectively.",
    status: "Applications Open",
    deadline: "Cohorts start monthly",
    detail: "Local Democracy Lab is a 6-week self-paced course covering the mechanics of local government: how city budgets are set, how zoning decisions get made, how school boards work, and how citizens can meaningfully participate in each. Participants complete a final 'civic audit' of one local institution and present it in a live virtual session. Certificate issued on completion.",
    cohortSize: "Open enrollment",
    location: "Fully virtual",
  },
  {
    id: 4,
    name: "Neighborhood Action Seed Grant",
    category: "Micro-Grant",
    ageRange: "14–24",
    duration: "3 months",
    format: "In-person, your community",
    skills: ["Collaborating to Create Solutions"],
    description: "Quick-turnaround seed support for young people ready to launch a neighborhood-scale civic project right now. Apply alone or with up to 3 peers.",
    status: "Applications Open",
    deadline: "Applications reviewed bi-weekly",
    detail: "The Neighborhood Action Seed Grant provides fast, lightweight support for young people with a concrete idea and a clear community to serve. Applicants submit a one-page project description and a simple budget. Awards are made within two weeks of application. Recipients are matched with a local civic mentor and participate in a 3-month check-in cohort with other grantees. Projects must be community-based and have at least one measurable outcome.",
    cohortSize: "15–20 grantees per cycle",
    location: "Your neighborhood",
  },
  {
    id: 5,
    name: "Civic Media Apprenticeship",
    category: "Apprenticeship",
    ageRange: "17–23",
    duration: "16 weeks",
    format: "In-person (select cities) + virtual",
    skills: ["Credible Information", "Productive Conversations"],
    description: "Apprenticeship pairing young people with local newsrooms and civic media organizations to develop journalism, data, and public communication skills.",
    status: "Applications Open",
    deadline: "April 15, 2026",
    detail: "The Civic Media Apprenticeship places young people with local newsrooms, public radio stations, municipal open-data teams, or civic communication offices for 16 weeks. Apprentices work 20 hours per week alongside practicing journalists, data journalists, or public communications professionals. The program includes weekly skill-building sessions across all cohort members and concludes with a published or presented final project. Currently active in Atlanta, Phoenix, Detroit, and Minneapolis, with virtual placements available nationally.",
    cohortSize: "32 apprentices",
    location: "Atlanta, Phoenix, Detroit, Minneapolis + virtual",
  },
  {
    id: 6,
    name: "Youth Policy Scholars",
    category: "Research Program",
    ageRange: "16–20",
    duration: "8 weeks (summer)",
    format: "Hybrid — 3 weeks in Washington D.C.",
    skills: ["Credible Information", "Productive Conversations"],
    description: "Summer research program where young people investigate a real policy question, produce a brief read by actual policymakers, and present findings on Capitol Hill.",
    status: "Applications Open",
    deadline: "March 31, 2026",
    detail: "Youth Policy Scholars is an 8-week summer program for high school juniors and seniors and first/second year college students with strong research and writing skills. Scholars are organized into teams of 4 and assigned a real policy question in consultation with a partnering congressional office or federal agency. The program includes 3 weeks of intensive in-person work in Washington D.C., followed by 5 weeks of remote research and writing. Final policy briefs are presented to the partnering office and published through C&S.",
    cohortSize: "40 scholars (10 teams)",
    location: "Washington D.C. + remote",
  },
  {
    id: 7,
    name: "Environmental Justice Organizing Institute",
    category: "Training Institute",
    ageRange: "18–26",
    duration: "5 days",
    format: "In-person residential",
    skills: ["Collaborating to Create Solutions", "Productive Conversations"],
    description: "Intensive 5-day residential training in community organizing, coalition-building, and advocacy strategy for young environmental justice leaders.",
    status: "Applications Open",
    deadline: "May 1, 2026",
    detail: "The Environmental Justice Organizing Institute brings together 50 young leaders from frontline communities for an immersive 5-day residential training. Participants learn the fundamentals of community organizing — power mapping, coalition building, campaign strategy, and running effective public meetings — applied specifically to environmental and climate justice contexts. The institute includes peer learning sessions, skills workshops, and an evening speaker series featuring experienced EJ organizers. A follow-on virtual cohort meets monthly for 6 months after the institute.",
    cohortSize: "50 participants",
    location: "Atlanta, GA (residential)",
  },
  {
    id: 8,
    name: "Digital Civic Tools Buildathon",
    category: "Buildathon",
    ageRange: "16–25",
    duration: "72 hours",
    format: "In-person (multiple cities)",
    skills: ["Collaborating to Create Solutions", "Credible Information"],
    description: "A 72-hour civic technology buildathon where young developers, designers, and organizers build tools that solve real community problems — judged by the communities themselves.",
    status: "Coming Soon",
    deadline: "Registration opens April 2026",
    detail: "The Digital Civic Tools Buildathon brings together teams of 3–5 young people with complementary skills — coding, design, community organizing, research — to build functional civic technology tools over 72 hours. Problem statements are sourced directly from community organizations in the host cities. Judging panels include both civic technologists and representatives from the community organizations whose problems are being addressed. Winning teams receive development support to deploy their tools with real users.",
    cohortSize: "200 participants across 5 cities",
    location: "Chicago, Houston, Boston, Oakland, Minneapolis",
  },
  {
    id: 9,
    name: "Civic Writing Residency",
    category: "Writing Program",
    ageRange: "18–24",
    duration: "4 months",
    format: "Fully virtual with monthly group calls",
    skills: ["Credible Information", "Productive Conversations"],
    description: "A writing development program for young people with something to say about civic life. Participants produce 3 published pieces with editorial mentorship throughout.",
    status: "Applications Open",
    deadline: "Rolling — next cohort starts May 1, 2026",
    detail: "The Civic Writing Residency pairs young writers with an experienced editor for a 4-month supported writing process. Each resident produces three pieces — ranging from reported essays to opinion pieces to community-based narratives — that are edited, fact-checked, and published through C&S's platform and partner outlets. The residency includes monthly group calls with all residents and guest appearances from civic journalists and essayists. Strong writing samples required; journalism experience not required.",
    cohortSize: "15 residents",
    location: "Fully virtual",
  },
];

export const programCategories = [
  "All Programs",
  "Fellowship",
  "Team Grant",
  "Micro-Grant",
  "Skills Pathway",
  "Apprenticeship",
  "Research Program",
  "Training Institute",
  "Buildathon",
  "Writing Program",
];

export const interestCategories = [
  { id: "environment", label: "Environment", icon: "🌿" },
  { id: "education", label: "Education", icon: "📚" },
  { id: "health", label: "Health", icon: "❤️" },
  { id: "justice", label: "Justice", icon: "⚖️" },
  { id: "technology", label: "Technology", icon: "💻" },
  { id: "arts", label: "Arts & Culture", icon: "🎨" },
  { id: "community", label: "Community Building", icon: "🤝" },
  { id: "democracy", label: "Democracy", icon: "🗳️" },
];

export const ageBrackets = [
  "14–15",
  "16–17",
  "18–20",
  "21–24",
  "25+",
];

export const skillProgress = [
  { skill: "Productive Conversations", percent: 45, color: "#C8942E" },
  { skill: "Credible Information", percent: 32, color: "#2A7B88" },
  { skill: "Collaborating to Create Solutions", percent: 28, color: "#8B6B3D" },
];

export const skillColors = {
  "Productive Conversations": { bg: "#C8942E", text: "#C8942E", bgLight: "rgba(200,148,46,0.12)" },
  "Credible Information": { bg: "#2A7B88", text: "#2A7B88", bgLight: "rgba(42,123,136,0.12)" },
  "Collaborating to Create Solutions": { bg: "#8B6B3D", text: "#8B6B3D", bgLight: "rgba(139,107,61,0.12)" },
  "Collaborating": { bg: "#8B6B3D", text: "#8B6B3D", bgLight: "rgba(139,107,61,0.12)" },
};

export const avatarColors = [
  "#C8942E", "#2A7B88", "#8B6B3D", "#4A7C59", "#5A6B8C", "#9B6B8A", "#6B8C5A", "#8C6B5A"
];

export const profile = {
  name: "Amara Johnson",
  display_name: "Amara J.",
  initials: "AJ",
  age: 19,
  location: "Atlanta, GA",
  bio: "Public health major at Spelman College. Passionate about food justice and community health in Southwest Atlanta.",
  skills: {
    productive_conversations: 72,
    credible_information: 58,
    collaborating: 45,
  },
  journey: [
    { stage: "Awareness", date: "Sep 2025", action: "Completed interest assessment and explored food justice resources", completed: true },
    { stage: "First Action", date: "Oct 2025", action: "Attended Atlanta Food Policy Council public meeting", completed: true },
    { stage: "Sustained Engagement", date: "Nov 2025 – Jan 2026", action: "Completed Credible Information pathway on food policy data", completed: true },
    { stage: "Community & Collaboration", date: "Feb 2026", action: "Joined Fresh Start Collective food access mapping project", completed: true },
    { stage: "Leadership & Investment", date: "Upcoming", action: "Recommended for Carnegie Young Leaders application", completed: false },
  ],
  recent_actions: [
    { date: "Mar 8, 2026", title: "Presented food access findings to community board", skill: "Productive Conversations", detail: "Presented research findings on food desert mapping to the Southwest Atlanta Community Board. 34 attendees. Board voted to include food access in their Q2 priority agenda." },
    { date: "Mar 2, 2026", title: "Mapped 14 food access points in SW Atlanta", skill: "Credible Information", detail: "Used the community mapping tool to document 14 food access points including grocery stores, food banks, community gardens, and farmers markets in Southwest Atlanta. Data contributed to the Fresh Start Collective research database." },
    { date: "Feb 22, 2026", title: "Co-facilitated peer discussion on food policy", skill: "Productive Conversations", detail: "Co-facilitated a 90-minute discussion with 12 peers on food policy advocacy strategies. Used the Productive Conversations framework to structure dialogue across different perspectives on policy approaches." },
    { date: "Feb 15, 2026", title: "Published analysis of USDA food desert data", skill: "Credible Information", detail: "Completed and published an analysis of USDA food desert designation data for Fulton County. Identified three neighborhoods that meet food desert criteria but are not currently designated. Analysis shared with Atlanta Food Policy Council." },
    { date: "Feb 8, 2026", title: "Joined Fresh Start Collective project team", skill: "Collaborating to Create Solutions", detail: "Officially joined the Fresh Start Collective, a team of 6 young people mapping food access in Atlanta and drafting a food access proposal for the South Side Community Board." },
  ],
  recommended_next_steps: [
    { type: "action", title: "Lead a Community Food Access Forum", description: "Organize a public forum bringing together residents, local businesses, and policy makers to discuss food access solutions in Southwest Atlanta.", skill: "Productive Conversations", button_text: "Start Planning" },
    { type: "program", title: "Carnegie Young Leaders", description: "Your civic engagement profile and project involvement suggest you are ready for Carnegie Young Leaders. Apply with your Fresh Start Collective team for project funding and coaching.", skill: "All Skills", button_text: "Start Application" },
  ],
};

export const portfolioSkillColors = {
  "Productive Conversations": "#C8942E",
  "Credible Information": "#2A7B88",
  "Collaborating to Create Solutions": "#8B6B3D",
  "All Skills": "#4A7C59",
};

export const peerPosts = [
  {
    id: 1,
    peerId: 1,
    date: "March 7, 2026",
    title: "What we learned running 8 voter registration tables in one semester",
    excerpt: "We hit our goal of 400 new registrations by November, but the real lesson was in what almost stopped us. Here's what actually works at community college campuses — and what doesn't.",
    body: "We started the fall semester with an ambitious goal: 400 new voter registrations across four Maricopa County community colleges before the October deadline. We hit 412. But the number almost doesn't matter compared to what we learned along the way.\n\nThe biggest surprise: Wednesday afternoons between 1–3pm were consistently our highest-traffic windows — not lunch, not after class. Students who've already finished their morning obligations but haven't fully switched off are the most receptive. We mapped this across all four campuses and the pattern held everywhere.\n\nThe hardest part wasn't logistics — it was the conversations with students who genuinely didn't believe their vote would matter. That's where our C&S Productive Conversations training paid off. We stopped trying to convince people and started asking questions. What would have to change for it to feel worth it? That single shift in approach changed the texture of almost every table conversation.\n\nNext semester we're training 12 new table captains. If you're doing similar work, I'd love to compare notes.",
    skill: "Collaborating",
    readTime: "4 min read",
  },
  {
    id: 2,
    peerId: 5,
    date: "February 28, 2026",
    title: "Building civic info in 8 languages: what the translation process taught me about trust",
    excerpt: "Accurate translation is table stakes. What actually builds trust with immigrant communities is something harder to systematize — and something I'm still figuring out.",
    body: "When I started building the multilingual civic information hub, I assumed the hardest part would be translation accuracy. It wasn't. Accurate translation is achievable. Trust is the real challenge.\n\nHere's what I mean. In our early testing, we had Vietnamese-language content that was technically correct but used formal government register that felt cold and bureaucratic to native speakers. Families we tested with understood the words but didn't feel like the information was *for* them. One grandmother told our community liaison: 'This sounds like a letter from an official, not from someone who wants to help.'\n\nWe rebuilt our style guide from scratch with community input — simpler sentences, first-person framing, explicit statements about who we are and why we built this. The difference in engagement was immediate.\n\nThe lesson I'd pass on: involve native speakers not just as translators but as editors of tone. And build in feedback loops from day one. We have a simple 'Was this helpful?' prompt on every page that feeds directly into our revision queue. It's unglamorous but it works.",
    skill: "Credible Information",
    readTime: "5 min read",
  },
  {
    id: 3,
    peerId: 4,
    date: "February 19, 2026",
    title: "Why I stopped calling it a 'mentorship program' — and what changed when I did",
    excerpt: "The word 'mentorship' was attracting the wrong dynamic. Once we reframed it as peer skill-sharing, everything — the applications, the conversations, the outcomes — shifted.",
    body: "For the first six months, we called it the Youth Civic Tech Mentorship Program. Applications came in, matches were made, but something felt off. The relationships were too transactional. Mentees were treating mentors like answer machines, and mentors were performing expertise rather than genuinely collaborating.\n\nI read some research on peer learning in civic contexts and had a hunch: the word 'mentorship' was loading the dynamic before anyone even met. It implied a hierarchy — one person has knowledge, the other receives it.\n\nSo we rebranded internally as a 'skill-sharing cohort.' Same people, same pairings, different framing. We also restructured the first meeting: instead of the 'mentor' presenting their background, both participants answer the same three questions about a civic problem they're stuck on.\n\nThe change was immediate and striking. Mentors started saying things like 'I hadn't thought about it that way.' Mentees brought ideas to meetings instead of questions. Three pairs have now built actual tools together.\n\nIf you're designing a peer learning program, I'd push you to interrogate the language before you launch. The framing shapes everything.",
    skill: "Productive Conversations",
    readTime: "4 min read",
  },
  {
    id: 4,
    peerId: 2,
    date: "February 11, 2026",
    title: "We mapped 200+ food resources in Atlanta. Here's what the data actually shows.",
    excerpt: "The map is live. But the most important finding isn't on it — it's in the gap between what residents know exists and what they actually trust enough to use.",
    body: "After six months of fieldwork, our food access map for metro Atlanta is live. We've documented 214 resources: food banks, community fridges, SNAP-accessible stores, community gardens, and meal programs. You can filter by neighborhood, hours, and whether identification is required.\n\nBut the most important thing we learned isn't visible on the map.\n\nIn nearly every community interview, we found the same pattern: residents knew about more resources than we expected, but many didn't use them because of trust barriers. A food pantry that requires proof of address. A community fridge that was stocked inconsistently. A program that had been helpful once but 'changed' in a way that made people feel unwelcome.\n\nThe map shows supply. It can't show the texture of trust. We're now building a second layer: a community review system where residents can leave short notes — not star ratings, just brief, honest accounts of their experience. We're piloting it in two zip codes before scaling.\n\nIf your organization runs a food resource and wants to understand how residents actually experience it, reach out. We're not trying to call anyone out. We're trying to build something honest.",
    skill: "Credible Information",
    readTime: "5 min read",
  },
  {
    id: 5,
    peerId: 7,
    date: "January 30, 2026",
    title: "How 14 students got a school board to actually listen — and what we're doing next",
    excerpt: "We didn't go in with demands. We went in with questions and data. The difference in how the board responded was something I didn't expect.",
    body: "Last fall, 14 students from across Minneapolis schools presented to the school board on mental health resources and curriculum equity. I want to be honest about what worked, what didn't, and what I'd do differently.\n\nWhat worked: we spent three weeks before the meeting doing structured interviews with 60 students across six schools. Not a survey — actual conversations, recorded with permission, transcribed and coded by theme. When we stood up to speak, we weren't sharing our opinions. We were presenting what our peers had told us, with their words.\n\nBoard members who had seemed disengaged during previous public comments were taking notes. One member asked us to send the full findings. Another asked if we'd be willing to participate in a working group on the mental health budget line.\n\nWhat didn't work: we underestimated how much time we'd need for preparation. The last week was genuinely stressful. If we do this again — and we will — I want to start the research phase a month earlier.\n\nWhat's next: we're being included in a district advisory session in April. That feels significant. But I want to be realistic — inclusion in a conversation is not the same as influence over an outcome. We're tracking our asks and will report back on what actually moves.",
    skill: "Productive Conversations",
    readTime: "6 min read",
  },
  {
    id: 6,
    peerId: 6,
    date: "January 22, 2026",
    title: "Community land trusts aren't complicated. Here's a plain-language explanation — and why it matters in Houston right now.",
    excerpt: "I've explained CLTs to hundreds of Third Ward residents over the past year. This is the version that actually lands.",
    body: "A community land trust is a nonprofit that owns land permanently, on behalf of a community, and leases it to residents at affordable rates. The homeowner owns their house. The trust owns the land. When the homeowner sells, the sale price is capped — they make a reasonable return, but not a speculative one. The next buyer pays an affordable price too.\n\nThe result: permanently affordable housing that can't be flipped by developers.\n\nIn Houston's Third Ward, we're watching the same displacement pattern that's hit historically Black neighborhoods in Austin, Atlanta, and Oakland. Property values rising 30–40% in five years. Long-term residents — many of them elderly, many of them renters — being priced out of communities their families built.\n\nA CLT won't solve all of this. But it can anchor specific blocks. It can protect specific families. It can give a community a formal mechanism to say: this land stays ours.\n\nWe're in the early stages of organizing support for a Third Ward CLT — building a coalition of residents, local churches, and advocacy organizations. If you're in Houston and want to get involved, or if you've worked on CLT organizing elsewhere and have lessons to share, I want to hear from you.",
    skill: "Productive Conversations",
    readTime: "5 min read",
  },
];
